# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x] # Versiones de Node.js que quieres probar
        # Puedes agregar más versiones si es necesario

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm" # Habilita la caché de npm para acelerar las instalaciones futuras

      - name: Install dependencies
        run: npm install # Usa npm install si no tienes un package-lock.json

      - name: Build the project
        run: npm run build --if-present # Compila el proyecto si el script build está presente

      - name: Run tests
        run: npm test # Ejecuta los tests del proyecto

